- name: Check OS
  shell: uname
  register: unameResult
  tags:
  - helm

- name: Download helm archive - Linux
  get_url:
    url: "https://storage.googleapis.com/kubernetes-helm/helm-{{ helm.version }}-{{ unameResult.stdout | lower }}-amd64.tar.gz"
    checksum: "{{ helm.checksumLinux }}"
    dest: "{{ helm.tmpDir }}"
  when:
    - (unameResult.stdout | lower) == "linux"
  tags:
    - helm

- name: Download helm archive - Mac
  get_url:
    url: "https://storage.googleapis.com/kubernetes-helm/helm-{{ helm.version }}-{{ unameResult.stdout | lower }}-amd64.tar.gz"
    checksum: "{{ helm.checksumMac }}"
    dest: "{{ helm.tmpDir }}"
  when:
    - (unameResult.stdout | lower) == "darwin"
  tags:
    - helm

- name: Create helm directory
  file:
    path: "{{ helm.tmpDir }}/helm-{{ helm.version }}"
    state: directory
    mode: 0755
  tags:
    - helm

- name: Unarchive helm
  unarchive:
    src: "{{ helm.tmpDir }}/helm-{{ helm.version }}-{{ unameResult.stdout | lower }}-amd64.tar.gz"
    dest: "{{ helm.tmpDir }}/helm-{{ helm.version }}"
  tags:
    - helm

- name: Copy helm binary to destination directory
  copy:
    src: "{{ helm.tmpDir }}/helm-{{ helm.version }}/{{ unameResult.stdout | lower }}-amd64/helm"
    dest: "{{ helm.binDir }}/helm"
    mode: 0755
  tags:
    - helm
