- name: Set fact for kubeStateMetrics tempdir
  set_fact:
    kubeStateMetricsTempDir: "/tmp/kubeStateMetrics-{{ ansible_date_time.iso8601_basic_short }}"
  tags:
    - kubeStateMetrics

- name: Copy templates and apply
  block:
    - name: Create kubeStateMetrics temp dir
      file:
        path: "{{ kubeStateMetricsTempDir }}"
        state: directory
        mode: 0755
      changed_when: false
      tags:
        - kubeStateMetrics

    - name: Copy kubeStateMetrics manifest jinja2 templates
      template:
        src: "kubeStateMetrics.yaml.j2"
        dest: "{{ kubeStateMetricsTempDir }}/kubeStateMetrics.yaml"
      changed_when: false
      tags:
        - kubeStateMetrics

    - name: Apply kubeStateMetrics manifest
      k8s:
        kubeconfig: "{{ configuration.k8sconfiguration.dest }}"
        state: "{{ configuration.kubeStateMetrics.state }}"
        src: "{{ kubeStateMetricsTempDir }}/kubeStateMetrics.yaml"
        namespace: "{{ configuration.kubeStateMetrics.namespace }}"
      tags:
        - kubeStateMetrics

    - name: Delete kubeStateMetrics temp dir
      file:
        path: "{{ kubeStateMetricsTempDir }}"
        state: absent
      changed_when: false
      tags:
        - kubeStateMetrics

  rescue:
    - name: Delete kubeStateMetrics temp dir
      file:
        path: "{{ kubeStateMetricsTempDir }}"
        state: absent
      changed_when: false
      tags:
        - kubeStateMetrics

    - name: Fail
      fail:
        msg: "Rescue was invoked, failing task."
      tags:
        - kubeStateMetrics
