apiVersion: v1
kind: Service
metadata:
  name: hello-k8s
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: hello-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
        version: "1"
    spec:
      containers:
        - name: hello-k8s
          image: paulbouwer/hello-kubernetes:1.7
          ports:
            - containerPort: 8080
          env:
            - name: MESSAGE
              value: Welcome to a POD!
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-k8s-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - hello-k8s.tflab-dev.xenit.io
      secretName: hello-k8s
  rules:
    - host: hello-k8s.tflab-dev.xenit.io
      http:
        paths:
          - path: /
            backend:
              serviceName: hello-k8s
              servicePort: 8080
